### ISSUE TITLE
Jukito doesn't seem to properly honor private modules.

### ISSUE THREAD

**Issue by jsievenpiper** [ArcBees/Jukito#68]
Not sure if the project is still being maintained, last commit looks like it was a couple years ago.. but here's hoping 😄 

I use private modules quite extensively in my projects to keep bindings as local as possible, however, I've noticed that if I install a private module in a Jukito test, classes that should be able to be injected with those bindings get mocks instead of the proper bindings. Creating a regular Guice injector and obtaining an instance of the same class sees the bindings as expected.

An example:

```
class ExampleModule extends PrivateModule {
    // Some thing that I'm testing.
    bind(ExampleInterface.class).to(ExampleImpl.class);
    expose(ExampleInterface.class);

    // Purposely not exposed.
    bind(PrivateInnerInterface.class).to(PrivateInnerImpl.class);
}

// elsewhere in test land:
public static class Module extends JukitoModule {

    @Override
    public void configureBindings() {
        install(new ExampleModule());
    }


    @Test
    public void testSomething(ExampleInterface example) {
        // ExampleInterface is concrete, as expected, but was injected with a
        // mock of PrivateInnerInterface, even though I'd expect it should
        // have a PrivateInnerImpl.
    }

}
```

Is this expected behavior? A limitation of the binding not being exposed?

**Comment by christiangoudreau** [comment]
That's a known limitation unfortunately. 

For the other part of the question, yes the projet is still being maintenant and heavily used. It just reached a point where it's mature and stable for its usage. :)

**Comment by jsievenpiper** [comment]
@christiangoudreau great to hear (that it's still being maintained)!

No worries, just figured I'd throw it on the radar -- is this something you are hoping to handle, or do you think it will remain a limitation? If so, we can just close this. Happy to know I wasn't crazy 😄

**Comment by mmadson** [comment]
@jsievenpiper I ran into this same limitation. Not sure if you figured out that the solution is for your Module to extend `TestModule` instead of `JukitoModule` and define it as a static inner class of your test class. To make this easier I've made some changes in a branch which defines a new property `autoBindMocks` on the `@UseModules` property. If it's set to false, then the modules that you define will not have any auto mocking performed and the duplicate bind exception shouldn't be a problem. You can grab the code from here:

https://github.com/mmadson/Jukito

Though I've also submitted a PR to ArcBees that you may want to track.

https://github.com/ArcBees/Jukito/pull/72

Good luck!
