### ISSUE TITLE
"already configured" error with PrivateModules and annotated bindings

### ISSUE THREAD

**Issue by lbtc-xxx** [ArcBees/Jukito#70]
*[Originally posted to Google Group](https://groups.google.com/forum/?fromgroups#!topic/jukito/3U_9_ByNrcg)*

I'm trying to use Jukito in a complicated situation which consists of multiple `PrivateModule`s and annotated bindings, but it doesn't work and looking for a help.

I pushed the reproducer and full stacktrace to https://github.com/lbtc-xxx/jukito-error . This problem can be reproduced with cloning this repo and simply executing `mvn clean test`.

This yields a `CreationException` which states "... A binding to app.ThirdPartyService was already configured at ...". But there is no duplicated binding in my modules, so it works well with  `Guice.createInjector().getInstance()`.

I created and exposed one annotated binding and one not annotated binding in [a PrivateModule](https://github.com/lbtc-xxx/jukito-error/blob/master/src/main/java/app/ThirdPartyPrivateModule.java), and apparently it doesn't play well with Jukito.

Is there any workaround to this situation?

**Comment by lbtc-xxx** [comment]
FYI:

* [A testcase with Jukito (does not work, produces an Exception)](https://github.com/lbtc-xxx/jukito-error/blob/master/src/test/java/app/JukitoTest.java)
* [A testcase without Jukito (works fine)](https://github.com/lbtc-xxx/jukito-error/blob/master/src/test/java/app/PlainTest.java)

**Comment by mmadson** [comment]
@lbtc-xxx 

I ran into the same problem and have submitted a PR to address the issue. You can track it here:

https://github.com/ArcBees/Jukito/pull/72

The problem is that the `@UseModules` annotation takes the defined modules and constructs a JukitoModule which attempts to bind mocks for any interfaces it thinks don't have bindings already defined. Obviously it can mess up. The TestModule class does not attempt to create these automatic bindings, so I've added a property `autoBindMocks` to the `@UseModules` annotation which if set to false the defined modules will be installed into a TestModule which does not create bindings to the mocks.

Until the PR gets merged the workaround is to define a public static inner class module which extends TestModule. Juktio will pickup this class very much like if you had used `@UseModules`:

```
@RunWith(JukitoRunner.class)
public class MyTestClass {
    public static class MyJukitoModule extends TestModule {
        @Override 
        public configureTests() {
            install(new SomeModuleYouWouldHavePlacedInUseModulesAnnotation());
        }
    }
  
    @Inject
    SomeInjectedClassThatDependsOnAnInterfaceInPrivateModule instance; 
}
```

**Comment by lbtc-xxx** [comment]
@mmadson
Thank you, I've just confirmed that the workaround which you suggested [works for me](https://github.com/lbtc-xxx/jukito-error/blob/master/src/test/java/app/JukitoWorkaroundTest.java), You are a lifesaver!
